### ISSUE TITLE
0syscall6.skprx reboots the Vita while on Standby

### ISSUE THREAD

**Issue by Altheon1994** [SKGleba/0syscall6#5] opened 2019-12-19 01:56 UTC
I'd like to report this issue again as stated on the title.

Unit: PS Vita 1000 (3G)
Firmware: 3.60 Henkaku (Enso)

I've been testing 0syscall6 with multiple scenarios as of late and altering it with ref00d since both does virtually the same job it seems.

Note: I used 0syscall6 and ref00d separately in this case. Not having both activated at the same time whatsoever.

**0syscall6 test results**
0sycall6 with ITLS = Rebooting in standby at an unspecified time
0syscall6 without ITLS (certificate also deleted) = Rebooting in standby at an unspecified time

**ref00d Test Results**
ref00d with ITLS = No reboots encountered in 6 hours
ref00d without ITLS (certificate also deleted) = No reboots for the rest of the day (Just checked this morning at 9:37 am GMT +8. Started this test around 10:24 pm GMT+8)

**Further notes:**

Wasn't using renga at all that I can confirm.

0syscall6 plugin was installed correctly as instructed under *KERNEL.
I strongly think the issue is worth looking into again

**Comment by Converted007** [comment] 2019-12-19 02:03
@SKGleba @Altheon1994 I have the exact same issue with the exact same Vita (1000 with 3G and firmware 3.60 Henkaku Enso).

As soon as i uninstalled 0syscall6 the random reboots in standby stopped. And i dont have psprenga installed at all...

So maybe worth a try looking into it because i think its not related to the pspsrenga issue, BUT a whole new issue.

**Comment by SKGleba** [comment] 2019-12-19 06:43
Well i marked it as a renga issue since 0syscall6 uses renga's nmprunner.

- What were the installed plugins?
- Did you sleep on an app or on shell/livearea?

**Comment by Altheon1994** [comment] 2019-12-20 00:18
> Well i marked it as a renga issue since 0syscall6 uses renga's nmprunner.
> 
> What were the installed plugins?
> Did you sleep on an app or on shell/livearea?

At the time I had these plugins installed (all set at ur0:tai) :

Under *Kernel
0syscall6.skprx
itls.skprx
ds4vita.skprx
nonpdrm.skprx
usbmc.skprx
udcd_uvc.skprx
bicr.skprx
adrenaline_kernel.skprx
repatch.skprx
PSVshell.skprx
ioplus.skprx

under *main
download_enabler.suprx
shellbat.suprx

under *NPXS10015
yamt.suprx

and under *ALL
itls.suprx
vitagrafix.suprx
vsh.suprx
InfiniteNet.suprx

As for sleep behavior:
Tried a mixed bag. I put it on sleep running Adrenaline and at other times on LiveArea.

**Comment by SKGleba** [comment] 2019-12-20 06:43
Ok, adrenaline may crash when waking up, this will be fixed in the next release.
I will test compatibility with other plugins and hopefully find the cause. Thanks!

**Comment by Converted007** [comment] 2019-12-20 22:53
> Well i marked it as a renga issue since 0syscall6 uses renga's nmprunner.
> 
> * What were the installed plugins?
> * Did you sleep on an app or on shell/livearea?

It did sleep on shell/livearea.

I have and had these plugins installed:

*KERNEL
ur0:tai/0syscall6.skprx
ur0:tai/nonpdrm.skprx
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
ur0:tai/storagemgr.skprx
ur0:tai/custom_boot_splash.skprx
ur0:tai/repatch.skprx
ur0:tai/reF00D.skprx
ur0:tai/AnalogsEnhancer.skprx
ur0:tai/PSVshell.skprx

*main
ur0:tai/henkaku.suprx
ur0:tai/shellbat.suprx
ur0:tai/volume_profile.suprx
ur0:tai/pngshot.suprx
ur0:tai/download_enabler.suprx
ur0:tai/custom_warning.suprx
ur0:tai/notrophymsg.suprx

*NPXS10015
ur0:tai/henkaku.suprx

*NPXS10016
ur0:tai/henkaku.suprx

*ITLS
*KERNEL
ur0:tai/itls.skprx
*ALL
ur0:tai/itls.suprx

**Comment by SKGleba** [comment] 2019-12-22 07:22
Should be fixed in latest

**Comment by Converted007** [comment] 2019-12-23 19:33
> Should be fixed in latest

Will test. Thanks

Edit: seems fixed on my vita. Didnt had a single reboot in standby for the last 2 days.

**Comment by Altheon1994** [comment] 2019-12-27 02:47
Thanks for the fix. Haven't encountered any restarts yet. It's been already 2 days on my end. I don't think it'll run into problems now.

**Closed as completed** 2019-12-27 02:49 UTC
